version: '3'
services:
  flask:
    image: app-flask
    build:
      context: .
      dockerfile: flask/Dockerfile
    volumes:
      - "./:/app"
  nginx:
    image: app-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - flask